const express = require("express");
const router = express.Router();
const { businessinsider } = require("../controller/businessinsider");
const { businessinsiderOld } = require("../controller/businessinsider/old");
const { dailyStarMain } = require("../controller/dailystar");
const { yStarMain } = require("../controller/y/index");
const { cointelegraph } = require("../controller/cointelegraph");
const { cointelegraphOld } = require("../controller/cointelegraph/old");
const { bucketlistly } = require("../controller/bucketlistly");
const { aljazeera } = require("../controller/aljazeera");
const { aljazeeraOld } = require("../controller/aljazeera/old");
const { theoooblog } = require("../controller/theoooblog");
const { seriouseats } = require("../controller/seriouseats");
const { thekitchn } = require("../controller/thekitchn");
const { threatpost } = require("../controller/threatpost");
const { threatpostOld } = require("../controller/threatpost/old");
const { cicnews } = require("../controller/cicnews");
const { cicnewsOld } = require("../controller/cicnews/old");
const { canadim } = require("../controller/canadim");
const { evisaimmigration } = require("../controller/evisaimmigration");
const { evisaimmigrationOld } = require("../controller/evisaimmigration/old");
const { cbc } = require("../controller/cbc");
const { cbcOld } = require("../controller/cbc/old");
const { letsexpresso } = require("../controller/letsexpresso");
const { letsexpressoOld } = require("../controller/letsexpresso/old");
const { fusionRead } = require("../controller/fusion");
const { redditblog } = require("../controller/redditblog");
const { redditblogOld } = require("../controller/redditblog/old");
const { revealnews } = require("../controller/revealnews");
const { revealnewsOld } = require("../controller/revealnews/old");
const { macresearch } = require("../controller/macresearch");
const { macresearchOld } = require("../controller/macresearch/old");
const { theatlantic } = require("../controller/theatlantic");
const { theatlanticOld } = require("../controller/theatlantic/old");
const { bitbucket } = require("../controller/bitbucket");
const { bitbucketOld } = require("../controller/bitbucket/old");
const { reuters } = require("../controller/reuters");
const { reutersOld } = require("../controller/reuters/old");
const { wsj } = require("../controller/wsj");
const { wsjOld } = require("../controller/wsj/old");
const { dev } = require("../controller/dev");
const { devOld } = require("../controller/dev/old");
const { stackabuse } = require("../controller/stackabuse");
const { stackabuseOld } = require("../controller/stackabuse/old");
const { propublica } = require("../controller/propublica");
const { propublicaOld } = require("../controller/propublica/old");
const { canadavisa } = require("../controller/canadavisa");
const { medium } = require("../controller/medium");
const { mediumOld } = require("../controller/medium/old");
const { bbc } = require("../controller/bbc");
const { cnet } = require("../controller/cnet");
const { cnetOld } = require("../controller/cnet/old");
const { rt } = require("../controller/rt");
const { nasa } = require("../controller/nasa");
const { nasaOld } = require("../controller/nasa/old");
const { yahoo } = require("../controller/yahoo");
const { foxnews } = require("../controller/foxnews");
const { danflyingsolo } = require("../controller/danflyingsolo");
const { lilistravelplans } = require("../controller/lilistravelplans");
const { mylifesamovie } = require("../controller/mylifesamovie");
const { theblogabroad } = require("../controller/theblogabroad");
const { nomadicboys } = require("../controller/nomadicboys");
const { backpackerbanter } = require("../controller/backpackerbanter");
const { travelbreak } = require("../controller/travel-break");
const { theblondeabroad } = require("../controller/theblondeabroad");
const { abrokenbackpack } = require("../controller/abrokenbackpack");
const { nytimes } = require("../controller/nytimes");
const { nytimesOld } = require("../controller/nytimes/old");
const { latimes } = require("../controller/latimes");
const { latimesOld } = require("../controller/latimes/old");
const { nypost } = require("../controller/nypost");
const { nypostOld } = require("../controller/nypost/old");
const { bostonglobe } = require("../controller/bostonglobe");
const { bostonglobeOld } = require("../controller/bostonglobe/old");
const { washingtonpost } = require("../controller/washingtonpost");
const { washingtonpostOld } = require("../controller/washingtonpost/old");
const { chicagotribune } = require("../controller/chicagotribune");
const { newsday } = require("../controller/newsday");

const { closeTime, testOld } = require("../controller/authController");

const infinityScroll = require("../controller/scroll");

router.get("/businessinsider", businessinsider);
router.post("/businessinsider/old", businessinsiderOld);
router.get("/thedailystar", dailyStarMain);
router.get("/y", yStarMain);
router.get("/fusionread", infinityScroll);
//router.get("/theoooblog", theOBlog);
router.get("/cointelegraph", cointelegraph);
router.post("/cointelegraph/old", cointelegraphOld);
router.get("/bucketlistly", bucketlistly);
router.get("/aljazeera", aljazeera);
router.post("/aljazeera/old", aljazeeraOld);
router.get("/theoooblog", theoooblog);
router.get("/seriouseats", seriouseats);
router.get("/thekitchn", thekitchn);
router.get("/threatpost", threatpost);
router.post("/threatpost/old", threatpostOld);
router.get("/cicnews", cicnews);
router.post("/cicnews/old", cicnewsOld);
router.get("/canadim", canadim);
router.get("/evisaimmigration", evisaimmigration);
router.post("/evisaimmigration/old", evisaimmigrationOld);
router.get("/cbc", cbc);
router.post("/cbc/old", cbcOld);
router.get("/letsexpresso", letsexpresso);
router.post("/letsexpresso/old", letsexpressoOld);
router.get("/fusionread", fusionRead);
router.get("/redditblog", redditblog);
router.post("/redditblog/old", redditblogOld);
router.get("/revealnews", revealnews);
router.post("/revealnews/old", revealnewsOld);
router.get("/macresearch", macresearch);
router.post("/macresearch/old", macresearchOld);
router.get("/theatlantic", theatlantic);
router.post("/theatlantic/old", theatlanticOld);
router.get("/bitbucket", bitbucket);
router.post("/bitbucket/old", bitbucketOld);
router.get("/reuters", reuters);
router.post("/reuters/old", reutersOld);
router.get("/wsj", wsj);
router.post("/wsj/old", wsjOld);
router.get("/dev", dev);
router.post("/dev/old", devOld);
router.get("/stackabuse", stackabuse);
router.post("/stackabuse/old", stackabuseOld);
router.get("/propublica", propublica);
router.post("/propublica/old", propublicaOld);
router.get("/canadavisa", canadavisa);
router.get("/medium", medium);
router.post("/medium/old", mediumOld);
router.post("/bbc/old", bbc);
router.get("/cnet", cnet);
router.post("/cnet/old", cnetOld);
router.get("/rt", rt);
router.get("/nasa", nasa);
router.post("/nasa/old", nasaOld);
router.get("/yahoo", yahoo);
router.get("/foxnews", foxnews);
router.get("/danflyingsolo", danflyingsolo);
router.get("/lilistravelplans", lilistravelplans);
router.post("/mylifesamovie/old", mylifesamovie);
router.get("/theblogabroad", theblogabroad);
router.get("/nomadicboys", nomadicboys);
router.get("/backpackerbanter", backpackerbanter);
router.get("/travel-break", travelbreak);
router.get("/theblondeabroad", theblondeabroad);
router.get("/abrokenbackpack", abrokenbackpack);
router.get("/nytimes", nytimes);
router.post("/nytimes/old", nytimesOld);
router.get("/latimes", latimes);
router.post("/latimes/old", latimesOld);
router.get("/nypost", nypost);
router.post("/nypost/old", nypostOld);
router.get("/bostonglobe", bostonglobe);
router.post("/bostonglobe/old", bostonglobeOld);
router.get("/washingtonpost", washingtonpost);
router.post("/washingtonpost/old", washingtonpostOld);
router.post("/chicagotribune/old", chicagotribune);
router.post("/newsday/old", newsday);

router.post("/close", closeTime);

module.exports = router;
